### ISSUE TITLE
Repeating taps have delay ?

### ISSUE THREAD

**Issue by YHSX88** [yuwang17/WYMaterialButton#2]
Hi 

I'm trying now the library and I found (sorry or at least I can't figure out) , if I want the user to double tap or tap very quickly one after another (because is not working for me) how this can be achieved and still the material effect to be there. 

Can you hep with this please.
Thanks in advance.

**Comment by yuwang17** [comment]
Alright, I've just enabled the user interaction during the material animation, so now you'll be able to tap the button as quick as you like :P 

Thanks for your suggestion. (Don't forget `pod update`)

**Comment by YHSX88** [comment]
Thanks Very Much :)

**Comment by yuwang17** [comment]
No problem. Thanks for supporting.
