### ISSUE TITLE
Failed to render IB Designables in Xcode 9, Swift 4

### ISSUE THREAD

**Issue by chris-gong** [yuwang17/WYMaterialButton#6]
Hey, this is very similar to an [old issue](https://github.com/Yu-w/WYMaterialButton/issues/3?_pjax=%23js-repo-pjax-container). Basically, it doesn't prevent my project from building successfully. It's just that my buttons won't preview in the storyboard. However when the project runs,  the buttons work as intended. I'm guessing this is an Xcode issue?
![screen shot 2018-01-11 at 2 42 27 pm](https://user-images.githubusercontent.com/13881485/34845004-85033a58-f6e1-11e7-8e3c-75c67a7e287f.png)
![screen shot 2018-01-11 at 2 45 18 pm](https://user-images.githubusercontent.com/13881485/34845005-8513780a-f6e1-11e7-9f33-3b829794964e.png)
![screen shot 2018-01-11 at 2 49 26 pm](https://user-images.githubusercontent.com/13881485/34845006-8523917c-f6e1-11e7-89b9-aa4b821e401b.png)
![screen shot 2018-01-11 at 2 51 30 pm](https://user-images.githubusercontent.com/13881485/34845007-853ad38c-f6e1-11e7-9a0f-89c82923ea36.png)

**Comment by Yu-w** [comment]
Indeed, Xcode seems not supporting well complex IB Designable component.
